// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZAWrctsJH5DCVRaHvekedpawDJjBEq9o',
    appId: '1:755198588899:web:3cd19aa578d8520b3392d6',
    messagingSenderId: '755198588899',
    projectId: 'flutter-burnner',
    authDomain: 'flutter-burnner.firebaseapp.com',
    storageBucket: 'flutter-burnner.appspot.com',
    measurementId: 'G-V8F9RZ0Q9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzayHo4veCh9HdOSqJVxOJ5iIwyePngs',
    appId: '1:755198588899:android:35c6addc0a9a126e3392d6',
    messagingSenderId: '755198588899',
    projectId: 'flutter-burnner',
    storageBucket: 'flutter-burnner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSLAapPI0Nmc1ijr_42LNKvlVSWQZXCtg',
    appId: '1:755198588899:ios:d03513ebace223203392d6',
    messagingSenderId: '755198588899',
    projectId: 'flutter-burnner',
    storageBucket: 'flutter-burnner.appspot.com',
    iosClientId: '755198588899-61ckhvjrdbbgs3remv921o1fu44hu7rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBurnner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSLAapPI0Nmc1ijr_42LNKvlVSWQZXCtg',
    appId: '1:755198588899:ios:d03513ebace223203392d6',
    messagingSenderId: '755198588899',
    projectId: 'flutter-burnner',
    storageBucket: 'flutter-burnner.appspot.com',
    iosClientId: '755198588899-61ckhvjrdbbgs3remv921o1fu44hu7rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBurnner',
  );
}
